
CREATE TABLE tblGioiTinh (
	MaGioiTinh varchar ( 2 )  NOT NULL,
	GioiTinh nvarchar ( 10 )  NULL,
CONSTRAINT PR_tblGioiTinh PRIMARY KEY CLUSTERED
(
	MaGioiTinh ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTrangThaiCanBo (
	MaTrangThaiCanBo varchar ( 2 )  NOT NULL,
	TenTrangThaiCanBo nvarchar ( 60 )  NULL,
CONSTRAINT PR_tblTrangThaiCanBo PRIMARY KEY CLUSTERED
(
	MaTrangThaiCanBo ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblDanToc (
	MaDanToc varchar ( 2 )  NOT NULL,
	TenDanToc nvarchar ( 60 )  NULL,
	TenKhac nvarchar ( 200 )  NULL,
CONSTRAINT PR_tblDanToc PRIMARY KEY CLUSTERED
(
	MaDanToc ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTonGiao (
	MaTonGiao varchar ( 2 )  NOT NULL,
	TenTonGiao nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTonGiao PRIMARY KEY CLUSTERED
(
	MaTonGiao ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTinh (
	MaTinh varchar ( 2 )  NOT NULL,
	TenTinh nvarchar ( 60 )  NULL,
	Cap nvarchar ( 60 )  NULL,
CONSTRAINT PR_tblTinh PRIMARY KEY CLUSTERED
(
	MaTinh ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblHuyen (
	MaHuyen varchar ( 3 )  NOT NULL,
	MaTinh varchar ( 2 )  NOT NULL,
	TenHuyen nvarchar ( 60 )  NULL,
	Cap nvarchar ( 20 )  NULL,
CONSTRAINT PR_tblHuyen PRIMARY KEY CLUSTERED
(
	MaHuyen ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblXa (
	MaXa varchar ( 5 )  NOT NULL,
	MaTinh varchar ( 2 )  NOT NULL,
	MaHuyen varchar ( 3 )  NOT NULL,
	TenXa nvarchar ( 60 )  NULL,
	Cap nvarchar ( 20 )  NULL,
CONSTRAINT PR_tblXa PRIMARY KEY CLUSTERED
(
	MaXa ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblViTriViecLam (
	MaViTriViecLam varchar ( 2 )  NOT NULL,
	TenViTriViecLam nvarchar ( 60 )  NULL,
CONSTRAINT PR_tblViTriViecLam PRIMARY KEY CLUSTERED
(
	MaViTriViecLam ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblNhomChucVu (
	MaNhomChucVu varchar ( 2 )  NOT NULL,
	MaViTriViecLam varchar ( 2 )  NULL,
	TenNhomChucVu nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblNhomChucVu PRIMARY KEY CLUSTERED
(
	MaNhomChucVu ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblHinhThucHopDong (
	MaHinhThucHopDong varchar ( 2 )  NOT NULL,
	TenHinhThucHopDong nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblHinhThucHopDong PRIMARY KEY CLUSTERED
(
	MaHinhThucHopDong ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblNgachHang (
	MaNgachHang varchar ( 10 )  NOT NULL,
	TenNgachHang nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblNgachHang PRIMARY KEY CLUSTERED
(
	MaNgachHang ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblNhiemVuKiemNhiem (
	MaNhiemVuKiemNhiem varchar ( 2 )  NOT NULL,
	TenNhiemVuKiemNhiem nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblNhiemVuKiemNhiem PRIMARY KEY CLUSTERED
(
	MaNhiemVuKiemNhiem ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblMonDay (
	MaMonDay varchar ( 2 )  NOT NULL,
	TenMonDay nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblMonDay PRIMARY KEY CLUSTERED
(
	MaMonDay ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblBacLuong (
	MaBacLuong varchar ( 2 )  NOT NULL,
	TenBacLuong nvarchar ( 60 )  NULL,
CONSTRAINT PR_tblBacLuong PRIMARY KEY CLUSTERED
(
	MaBacLuong ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblKQBDThuongXuyen (
	MaKQBDThuongXuyen varchar ( 2 )  NOT NULL,
	TenKQBDThuongXuyen nvarchar ( 60 )  NULL,
CONSTRAINT PR_tblKQBDThuongXuyen PRIMARY KEY CLUSTERED
(
	MaKQBDThuongXuyen ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTrDoChuyenMonNghiepVu (
	MaTrDoChuyenMonNghiepVu varchar ( 2 )  NOT NULL,
	TenTrDoChuyenMonNghiepVu nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTrDoChuyenMonNghiepVu PRIMARY KEY CLUSTERED
(
	MaTrDoChuyenMonNghiepVu ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTroDoLLCT (
	MaTrDoLLCT varchar ( 2 )  NOT NULL,
	TenTrDoLLCT nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTroDoLLCT PRIMARY KEY CLUSTERED
(
	MaTrDoLLCT ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblDanhMucNgoaiNgu (
	MaNgoaiNgu varchar ( 2 )  NOT NULL,
	TenNgoaiNgu nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblDanhMucNgoaiNgu PRIMARY KEY CLUSTERED
(
	MaNgoaiNgu ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTrDoNgoaiNgu (
	MaTrDoNgoaiNgu varchar ( 2 )  NOT NULL,
	TenTrDoNgoaiNgu nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTrDoNgoaiNgu PRIMARY KEY CLUSTERED
(
	MaTrDoNgoaiNgu ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTroDoTinHoc (
	MaTrDoTinHoc varchar ( 2 )  NOT NULL,
	TenTrDoTinHoc nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTroDoTinHoc PRIMARY KEY CLUSTERED
(
	MaTrDoTinHoc ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblTrDoQLGD (
	MaTrDoQLGD varchar ( 2 )  NOT NULL,
	TenTrDoQLGD nvarchar ( 100 )  NULL,
CONSTRAINT PR_tblTrDoQLGD PRIMARY KEY CLUSTERED
(
	MaTrDoQLGD ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
CREATE TABLE tblLoaiTotNghiepTHPT (
	MaLoaiTotNghiepTHPT varchar ( 2 )  NOT NULL,
	TenLoaiTotNghiepTHPT nvarchar ( 30 )  NULL,
CONSTRAINT PR_tblLoaiTotNghiepTHPT PRIMARY KEY CLUSTERED
(
	MaLoaiTotNghiepTHPT ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
)ON [PRIMARY]
